A=imread('D:\хр\lab_7\AJ.png');
A_R=A(:,:,3);
A_G=A(:,:,2);
A_B=A(:,:,1);
subplot(2,2,1);
imshow(A) ;
title ('RGB');
subplot(2,2,2);
imshow(A_B);
title('Blue channel');
subplot (2,2,3);
imshow(A_G) ;
title('Green channel');
subplot(2,2,4);
imshow(A_R);
title('Red channel');
saveas (gcf, 'MyFigure.png');
figure;
comb_lily(:,:,1)=A_R; comb_lily(:,:,2)=A_G; comb_lily(:,:,3)=A_B;
comb_lily=uint8(comb_lily);
imshow(comb_lily);
title('lily combined from separated channels');
